### ISSUE TITLE
Feasibility to use this with keycloak running on aws EC2

### ISSUE THREAD

**Issue by luojiakickoff** [kilmajster/keycloak-username-password-attribute-authenticator#11] opened 2022-08-30 08:43 UTC
Hello.

I am trying to customize the login screen of keycloak. I need to make user login with three fields but not only username and password. I feel that this authenticator is just right for me.

And my problem is that, I built my keycloak on aws ec2 , and I tried to put the jar package of this authenticator into `{$KEYCLOAK_PATH}/standalone/deployments/,` but it was not successfully deployed. Below is what occured in the `{$KEYCLOAK_PATH}/standalone/deployments/` after copying the jar package there.

> [root@ip-10-1-10-201 /]# cd /opt/keycloak-12.0.4/standalone/deployments/
[root@ip-10-1-10-201 deployments]# ll
total 36
-rw-r--r-- 1 root root 16604 Aug 30 07:55 keycloak-username-password-attribute-authenticator-0.3.0.jar
-rw-r--r-- 1 root root   778 Aug 30 07:55 keycloak-username-password-attribute-authenticator-0.3.0.jar.failed
-rw-r--r-- 1 root root  8888 Mar  1  2021 README.txt

Does it means that i can not bundle this authenticator together with keycloak by just deploying the jar file?

**Comment by kilmajster** [comment] 2022-08-30 11:26
Hi @luojiakickoff, I just checked that, and I believe the problem is caused by too much mismatch between versions of Keycloak you're running (12.0.4) and Keycloak API used in this project (16.1.1). When I'm locally running KC 12 with this authenticator there is a similar problem that you're facing, but with version 16.1.1 everything is good. Can you check with 16.1.1?

**Comment by luojiakickoff** [comment] 2022-08-31 01:36
@kilmajster Thanks for your quick answer. 

I have tried the version 16.1.1 and it seems that it does not work for me. I used this [keycloak zip](https://github.com/keycloak/keycloak/releases/download/16.1.1/keycloak-16.1.1.zip), and after making it successfully run, i downloaded [this jar file](https://github.com/kilmajster/keycloak-username-password-attribute-authenticator/releases/download/0.3.0/keycloak-username-password-attribute-authenticator-0.3.0.jar) and moved it to the `/tmp` folder, and then copy it to the `{$KEYCLOAK_PATH}/standalone/deployments/`. But there was still an jar.failed file there.

**Comment by kilmajster** [comment] 2022-08-31 03:11
I just checked this and for me it working fine, can you please provide Keycloka startup logs, or logs from the moment you are coping provider into `${KEYCLOAK_PATH}/standalone/deployments` ?

**Comment by luojiakickoff** [comment] 2022-08-31 04:23
Below is part of the logs in the `${KEYCLOAK_PATH}/standalone/log/server.log`.

> 2022-08-31 01:21:15,566 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."keycloak-username-password-attribute-authenticator-0.3.0.jar".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."keycloak-username-password-attribute-authenticator-0.3.0.jar".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "keycloak-username-password-attribute-authenticator-0.3.0.jar"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:189)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.UnsupportedClassVersionError: Failed to link io/github/kilmajster/keycloak/UsernamePasswordAttributeFormFactory (Module "deployment.keycloak-username-password-attribute-authenticator-0.3.0.jar" from Service Module Loader): io/github/kilmajster/keycloak/UsernamePasswordAttributeFormFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:832)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:351)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:276)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:79)
	at org.jboss.modules.Module.loadModuleClass(Module.java:753)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:192)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.keycloak.provider.DefaultProviderLoader.load(DefaultProviderLoader.java:60)
	at org.keycloak.provider.ProviderManager.load(ProviderManager.java:94)
	at org.keycloak.services.DefaultKeycloakSessionFactory.loadFactories(DefaultKeycloakSessionFactory.java:294)
	at org.keycloak.services.DefaultKeycloakSessionFactory.deploy(DefaultKeycloakSessionFactory.java:154)
	at org.keycloak.provider.ProviderManagerRegistry.deploy(ProviderManagerRegistry.java:42)
	at org.keycloak.subsystem.server.extension.KeycloakProviderDeploymentProcessor.deploy(KeycloakProviderDeploymentProcessor.java:58)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)
	... 8 more

> 2022-08-31 01:21:15,577 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "keycloak-username-password-attribute-authenticator-0.3.0.jar")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"keycloak-username-password-attribute-authenticator-0.3.0.jar\".POST_MODULE" => "WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"keycloak-username-password-attribute-authenticator-0.3.0.jar\"
    Caused by: java.lang.UnsupportedClassVersionError: Failed to link io/github/kilmajster/keycloak/UsernamePasswordAttributeFormFactory (Module \"deployment.keycloak-username-password-attribute-authenticator-0.3.0.jar\" from Service Module Loader): io/github/kilmajster/keycloak/UsernamePasswordAttributeFormFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"}}
2022-08-31 01:21:15,697 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0010: Deployed "keycloak-username-password-attribute-authenticator-0.3.0.jar" (runtime-name : "keycloak-username-password-attribute-authenticator-0.3.0.jar")
2022-08-31 01:21:15,698 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."keycloak-username-password-attribute-authenticator-0.3.0.jar".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "keycloak-username-password-attribute-authenticator-0.3.0.jar"

> 2022-08-31 03:00:46,422 WARN  [org.wildfly.extension.elytron] (default task-8) WFLYELY01085: Generated self-signed certificate at /opt/keycloak-16.1.1/standalone/configuration/application.keystore. Please note that self-signed certificates are not secure and should only be used for testing purposes. Do not use this self-signed certificate in production.
SHA-1 fingerprint of the generated key is 71:77:41:fb:3f:80:c3:7f:de:0e:e5:1a:53:05:08:b2:ac:3e:59:f4
SHA-256 fingerprint of the generated key is 4b:2a:99:d1:f9:48:5b:e7:e4:d7:bd:de:03:67:f0:4d:13:8d:19:f6:46:45:63:28:72:3b:1c:9f:bb:db:75:d9

Is this the right useful log for you?

**Comment by luojiakickoff** [comment] 2022-08-31 09:13
My bad. I did not notice the version of java jdk and wrongly used the jdk 1.8 version. And i successfully deploy the jar file when i change it to jdk11. Thanks again for your answer!

**Comment by kilmajster** [comment] 2022-08-31 13:09
Great to hear that you resolve the issue :D  I am closing this one, good luck!

**Closed as completed by kilmajster** 2022-08-31 13:09 UTC
